### PR TITLE
Fix/improve requirements.txt (issue #39)

### PR DESCRIPTION
**Pull request by antithalian**
When I tried to set up pork-chop for some dev work, `pip` failed to install everything at first because version 1.1.0 of `ChatterBot` was yanked from PyPI by the developer, so I downgraded it to the last stable version, 1.0.5, in requirements.txt. While looking at requirements.txt, I noticed that it was pretty large, and so I tried to pare it down to just what's imported by pork-chop (along with `chatterbot-corpus` since that's required by `ChatterBot` to train models).

I *think* everything runs fine with the changes I made, but I can't fully test because I don't currently have anything up and running that could serve as an endpoint for GroupMe's callbacks. Please let me know if this breaks anything, will fix ASAP.

### CODE REVIEW

**Comment by danerwilliams** [comment]
Could you try the new requirements.txt by using a virtual environment?

**Comment by antithalian** [comment]
Yeah, sure. Still won't be able to actually have the bot respond to test messages because I don't have a server to set as my endpoint, but I can make sure everything up until the web server launching works.

**Comment by danerwilliams** [comment]
Yeah I just want to make sure that pip installing from the requirements.txt file will cover everything so that running pork-chop.py will run right away.

**Comment by antithalian** [comment]
Just finally got around to checking things in a venv, and it looks solid. 

Pip does complain about a version mismatch in PyYAML when installing chatterbot-corpus, but that appears to be a known issue with chatterbot-corpus ([per their issue #127](https://github.com/gunthercox/chatterbot-corpus/issues/1270) chatterbot requires one version while chatterbot-corpus claims to require another). When I tested starting things up, it ran just fine, so I think it's a conflict in name rather than functionality. Unless we want to make people install from source, we'll have to wait for them to fix it.

I don't want to give a 100% OK to merge until it's been tested all the way through to talking to the bot, so @danerwilliams do you think you could do a test deploy? I'd do it, but as I said before, I don't currently have any web-facing servers I can use as endpoints for testing.

**Pull request merged**
